//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControledeEstoque.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaixaOrdem
    {
        public long BaixaOrdemID { get; set; }
        public long EstoqueID { get; set; }
        public long Quantidade { get; set; }
        public string Date { get; set; }
    }
}
