//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControledeEstoque.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public long ProductID { get; set; }
        public string CustomerCod { get; set; }
        public string PanalpinaCod { get; set; }
        public long MaterialType { get; set; }
        public long MaterialSubType { get; set; }
        public string Product { get; set; }
        public long MeasureUnit { get; set; }
        public string Comments { get; set; }
        public string ImagePath { get; set; }
        public string CreateDate { get; set; }
    }
}
